---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmware-topology-node-role
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmware-topology-secrets-role
  namespace: vmware-topology
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmware-topology-node-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: vmware-topology
roleRef:
  kind: ClusterRole
  name: vmware-topology-node-role
  apiGroup: rbac.authorization.k8s.io
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmware-topology-secret-binding
  namespace: vmware-topology
subjects:
- kind: ServiceAccount
  name: default
  namespace: vmware-topology
roleRef:
  kind: Role
  name: vmware-topology-secrets-role
  apiGroup: rbac.authorization.k8s.io
...
